In [1]:
import csv
import pandas as pd
from itertools import islice
import h5py
import numpy as np
from scipy import sparse
import re

/tmp/ipykernel_7332/2848238078.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Import data

In [86]:
file = 'consensus_clusters_tpm.csv'

data = pd.read_csv(file, sep = ',', header = 0)

data

,Region,s15t1p2sq1,s15t2p2sq1,s15t3p2sq1,s15t4p2sq1,s15t5p2sq1,s15t6p2sq1,s15t7p2sq1,s15t8p2sq1,s1t1p1sq1,...,MDAMB231crmdrep1,MDAMB231crmdrep2,Me16CcdHMECdRepd1,Me16CcdHMECdRepd2,ZRd75d1dRepd3,ZRd75d1dRepd4,ZRd75d1Repd1,ZRd75d1Repd2,ZRd75d30Repd1,ZRd75d30Repd2
0,chr1:629175-629265:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,110.266253,98.925682
1,chr1:629806-629930:+,0.000000,0.259874,0.000000,0.000000,0.000000,0.000000,0.159497,0.0,0.144932,...,0.431663,0.148921,0.000000,0.317584,0.971207,0.267795,1.280505,2.318278,8.685275,4.856002
2,chr1:630223-630315:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.148921,0.000000,0.000000,0.223255,0.154746,0.000000,0.000000,0.218153,0.000000
3,chr1:631294-631361:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,20.443834,17.180723,0.182066,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,chr1:632231-632378:+,0.000000,0.000000,0.000000,0.000000,0.049271,0.049293,0.000000,0.0,0.000000,...,0.000000,0.046636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.457854,8.808877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24693,chrUn_KI270438v1:109820-110002:-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.128586,0.093273,1.253179,2.591921,4.932149,6.839729,2.579147,2.878873,4.958816,7.729800
24694,chrUn_KI270744v1:6128-6215:-,1.317066,0.789345,0.092825,0.188534,0.096010,0.306186,0.000000,0.0,0.443378,...,0.000000,0.000000,20.900049,31.272995,0.823424,0.577287,1.099023,0.219339,0.000000,0.662847
24695,chrUn_KI270744v1:105258-105259:-,0.000000,0.000000,0.046413,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24696,chrUn_KI270744v1:112243-112244:-,0.524793,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24697,chrUn_KI270746v1:52556-52562:-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## Completing the chromosomal coordinates

In [ ]:
def adjust_coordinates(position):
    """
    If the end is missing in the coordinate, add the start as the end.
    
    Takes the column with the chromosomal position as input.
    Adds a column to the data frame with the correction of missing values.
    
    """
    full_format_regex = r'(chr[\w]+):(\d+)-(\d+):([\+\-])'
    
    # If the position matches the description.
    match = re.match(full_format_regex, position)
    if match:
        return position  
    
    # Else, add the start as the end.
    chromosome, start, strand = re.match(r'(chr[\w]+):(\d+):([\+\-])', position).groups()
    return f"{chromosome}:{start}-{start}:{strand}"

In [100]:
df_adjust_coordinates = pd.DataFrame(data)

# Insert the new column.
df_adjust_coordinates.insert(1, 'adjusted_coordinate', data['Region'].apply(adjust_coordinates))

df_adjust_coordinates

,Region,adjusted_coordinate,s15t1p2sq1,s15t2p2sq1,s15t3p2sq1,s15t4p2sq1,s15t5p2sq1,s15t6p2sq1,s15t7p2sq1,s15t8p2sq1,...,MDAMB231crmdrep1,MDAMB231crmdrep2,Me16CcdHMECdRepd1,Me16CcdHMECdRepd2,ZRd75d1dRepd3,ZRd75d1dRepd4,ZRd75d1Repd1,ZRd75d1Repd2,ZRd75d30Repd1,ZRd75d30Repd2
0,chr1:629175-629265:+,chr1:629175-629265:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,110.266253,98.925682
1,chr1:629806-629930:+,chr1:629806-629930:+,0.000000,0.259874,0.000000,0.000000,0.000000,0.000000,0.159497,0.0,...,0.431663,0.148921,0.000000,0.317584,0.971207,0.267795,1.280505,2.318278,8.685275,4.856002
2,chr1:630223-630315:+,chr1:630223-630315:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.148921,0.000000,0.000000,0.223255,0.154746,0.000000,0.000000,0.218153,0.000000
3,chr1:631294-631361:+,chr1:631294-631361:+,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,20.443834,17.180723,0.182066,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,chr1:632231-632378:+,chr1:632231-632378:+,0.000000,0.000000,0.000000,0.000000,0.049271,0.049293,0.000000,0.0,...,0.000000,0.046636,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.457854,8.808877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24693,chrUn_KI270438v1:109820-110002:-,chrUn_KI270438v1:109820-110002:-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.128586,0.093273,1.253179,2.591921,4.932149,6.839729,2.579147,2.878873,4.958816,7.729800
24694,chrUn_KI270744v1:6128-6215:-,chrUn_KI270744v1:6128-6215:-,1.317066,0.789345,0.092825,0.188534,0.096010,0.306186,0.000000,0.0,...,0.000000,0.000000,20.900049,31.272995,0.823424,0.577287,1.099023,0.219339,0.000000,0.662847
24695,chrUn_KI270744v1:105258-105259:-,chrUn_KI270744v1:105258-105259:-,0.000000,0.000000,0.046413,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24696,chrUn_KI270744v1:112243-112244:-,chrUn_KI270744v1:112243-112244:-,0.524793,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24697,chrUn_KI270746v1:52556-52562:-,chrUn_KI270746v1:52556-52562:-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

# Create bed file (peaks coordinates)

In [ ]:
def create_bed_file(df_peak_position, output_file='peaks.bed'):
    """
    Creates a BED file from peak coordinates in a pandas DataFrame.

    Args:
    - df_peak_position (pd.Series): A pandas Series containing peak coordinates.
    - output_file (str): The output BED file name. Default is 'peaks.bed'.
    """
    # Extract the information of chromosome, start, end.
    bed_data = df_peak_position.str.extract(r'(chr[\w]+):(\d+)-(\d+)', expand=True)

    # Write into a BED file.
    bed_data.to_csv(output_file, sep='\t', index=False, header=False)

    print(f"Successfully created BED file: {output_file}")

In [125]:
# Extract the information of the peaks coordinates from the adjusted data.
df_peak_position = df_adjust_coordinates['adjusted_coordinate']

# Extract the information of chromosome, start, end.
bed_data = df_peak_position.str.extract(r'(chr[\w]+):(\d+)-(\d+)', expand=True)

# Write into a BED file.
bed_file = 'peaks.bed'
bed_data.to_csv(bed_file, sep='\t', index=False, header=False)

# Print confirmation message.
print(f"Successfully created BED file: {bed_file}")

Successfully created BED file: peaks.bed

In [131]:
peak = pd.read_csv('peaks.bed', sep='\t', names=['chr','start','end'])
peak

                    chr   start     end
0                  chr1  629175  629265
1                  chr1  629806  629930
2                  chr1  630223  630315
3                  chr1  631294  631361
4                  chr1  632231  632378
...                 ...     ...     ...
24693  chrUn_KI270438v1  109820  110002
24694  chrUn_KI270744v1    6128    6215
24695  chrUn_KI270744v1  105258  105259
24696  chrUn_KI270744v1  112243  112244
24697  chrUn_KI270746v1   52556   52562

[24698 rows x 3 columns]

# Create count matrix H5 file

## Extract the usefull informations

In [141]:
# Extract the barcodes (patient IDs), features (peaks), and count matrix from the CSV file.

# Barcodes
barcodes = data.columns[1:]
barcodes_list = list(barcodes.astype(str))

# Features
features = df_peak_position
features_list = list(features.astype(str))
num_features = len(features_list)
feature_types_data = np.array(['Peaks'] * len(features_list), dtype='S20')
genome_data = np.array(['GRCh38'] * len(features_list), dtype='S20')

# Count matrix
data_matrix = data.iloc[:, 1:].values
data_matrix_transposed = np.transpose(data_matrix)  # Barcodes (patients) in rows and peaks in columns

print("Number of barcodes (patients): ", data_matrix_transposed.shape[0])
print("Number of peaks: ", data_matrix_transposed.shape[1])

Number of barcodes (patients):  98
Number of peaks:  24698

## Create the h5 file

In [156]:
# Create the h5 file and the respective groups

with h5py.File('count_matrix.h5', 'w') as f:
    # Create the /matrix group
    grp_matrix = f.create_group('matrix')
    
    # Write the barcodes into the /matrix/barcodes dataset
    grp_matrix.create_dataset('barcodes', data=barcodes_list)
    
    # Convert the count matrix to CSR format
    data_csr = sparse.csr_matrix(data_matrix_transposed)

    # Write the count matrix CSR into the /matrix/data dataset
    grp_matrix.create_dataset('data', data=data_csr.data)
    
    # Invert the dimensions of the matrix
    data_matrix_shape = data_csr.shape
    data_matrix_shape_inverse = (data_matrix_shape[1], data_matrix_shape[0])
    
    # Write the inverted shape into the /matrix/shape dataset
    grp_matrix.create_dataset('shape', data=data_matrix_shape_inverse)
    
    # Write the indices into the /matrix/indices dataset
    grp_matrix.create_dataset('indices', data=data_csr.indices)
    
    # Write the pointers into the /matrix/indptr dataset
    grp_matrix.create_dataset('indptr', data=data_csr.indptr)
    
    # Create the /matrix/features group
    grp_features = grp_matrix.create_group('features')
    
    # Write information about the features
    grp_features.create_dataset('_all_tag_keys', data=features_list)
    grp_features.create_dataset('feature_type', data=feature_types_data)
    grp_features.create_dataset('genome', data=genome_data)
    grp_features.create_dataset('id', data=features_list)
    grp_features.create_dataset('interval', data=features_list)
    grp_features.create_dataset('name', data=features_list)

    print(f"Successfully created count_matrix.h5 file")

Successfully created count_matrix.h5 file

In [3]:
def Visualize_h5_file(file_name, group):
    """
    Visualize the contents of an HDF5 file.

    Parameters:
    - file_name (str): The name of the HDF5 file.
    - group (str): The name of the group within the HDF5 file.

    """
    with h5py.File(file_name, 'r') as f:
        # Retrieve the keys of the HDF5 file
        keys = list(f.keys())
        print(f"Keys available in the HDF5 file: {keys}\n")

        # Access the specified group
        group_data = f[group]

        # Iterate over each member of the group
        for member in group_data.keys():
            # Check if the member is a group or a dataset
            if isinstance(group_data[member], h5py.Group):
                # If it's a group, display its keys
                print(f"Keys of subgroup '{member}':", list(group_data[member].keys()))
            else:
                # Otherwise, display the dataset's value
                dimensions = group_data[member].shape
                print(f"Dimension: {dimensions}")
                print(f"Value of dataset '{member}':", group_data[member][:])


Visualize_h5_file('count_matrix.h5', 'matrix')

Keys available in the HDF5 file: ['matrix']

Dimension: (98,)
Value of dataset 'barcodes': [b's15t1p2sq1' b's15t2p2sq1' b's15t3p2sq1' b's15t4p2sq1' b's15t5p2sq1'
 b's15t6p2sq1' b's15t7p2sq1' b's15t8p2sq1' b's1t1p1sq1' b's1t2p1sq1'
 b's1t3p1sq1' b's1t4p1sq1' b's1t5p2sq1' b's1t6p2sq1' b's1t7p2sq1'
 b's1t8p2sq1' b's7t1p1sq1' b's7t2p1sq1' b's7t3p1sq1' b's7t4p1sq1'
 b's7t5p1sq1' b's7t6p1sq1' b's7t7p1sq1' b's7t8p1sq1' b's2t1p3sq2'
 b's2t2p3sq2' b's2t3p3sq2' b's2t4p3sq2' b's2t5p3sq2' b's2t6p3sq2'
 b's2t7p3sq2' b's2t8p3sq2' b's3t1p3sq2' b's3t2p3sq2' b's3t3p3sq2'
 b's3t4p3sq2' b's3t5p4sq2' b's3t6p4sq2' b's3t7p4sq2' b's3t8p4sq2'
 b's4t1p4sq2' b's4t2p4sq2' b's4t3p4sq2' b's4t4p4sq2' b's4t5p4sq2'
 b's4t6p4sq2' b's4t7p4sq2' b's4t8p4sq2' b's5t1p5sq3' b's5t2p5sq3'
 b's5t3p5sq3' b's5t4p5sq3' b's5t5p5sq3' b's5t6p5sq3' b's5t7p5sq3'
 b's5t8p5sq3' b's6t1p5sq3' b's6t2p5sq3' b's6t3p5sq3' b's6t4p5sq3'
 b's6t5p6sq3' b's6t6p6sq3' b's6t7p6sq3' b's6t8p6sq3' b's9t1p6sq3'
 b's9t2p6sq3' b's9t3p6sq3' b's9t4p6sq3' b's9t5p6sq3' b's9t6p6sq3'
 b's9t7p6sq3' b's9t8p6sq3' b'AU565Repd1' b'AU565Repd2' b'HCC1937drep1'
 b'HCC1937drep2' b'HCC1954Repd1' b'HCC1954Repd2' b'HTBd26Repd1'
 b'HTBd26Repd2' b'MCF10Adrep1' b'MCF10Adrep2' b'MCF7drep1' b'MCF7drep2'
 b'MDAdMBd436Repd1' b'MDAdMBd436Repd2' b'MDAdMBd468dRepd3'
 b'MDAdMBd468dRepd4' b'MDAMB231crmdrep1' b'MDAMB231crmdrep2'
 b'Me16CcdHMECdRepd1' b'Me16CcdHMECdRepd2' b'ZRd75d1dRepd3'
 b'ZRd75d1dRepd4' b'ZRd75d1Repd1' b'ZRd75d1Repd2' b'ZRd75d30Repd1'
 b'ZRd75d30Repd2']
Dimension: (1702052,)
Value of dataset 'data': [53.08068685  0.78551056  6.71522754 ... 13.13042277  7.72980003
  0.66284687]
Keys of subgroup 'features': ['_all_tag_keys', 'feature_type', 'genome', 'id', 'interval', 'name']
Dimension: (1702052,)
Value of dataset 'indices': [    5     6     7 ... 24692 24693 24694]
Dimension: (99,)
Value of dataset 'indptr': [      0   15261   35859   56112   76308   96948  116524  136246  155241
  175505  195212  215604  236251  255331  275237  294722  312453  332696
  353014  373122  393429  413542  432146  452307  472379  486745  502794
  522548  541377  560422  578146  596703  612970  630898  646031  664090
  682601  700304  716967  733203  750049  763418  775577  788001  800375
  813504  826693  840962  858635  875744  891494  907399  922685  938782
  953625  970673  988878 1007582 1025989 1044673 1061863 1079978 1097957
 1116826 1134752 1151673 1169294 1185628 1204696 1222974 1238705 1257974
 1277749 1292898 1308241 1326438 1344580 1361887 1379130 1394198 1409179
 1425604 1442240 1459984 1477403 1491470 1506659 1524075 1541427 1558381
 1575908 1591499 1607527 1624313 1641833 1658835 1672866 1687893 1702052]
Dimension: (2,)
Value of dataset 'shape': [24698    98]

## visualize the anndata file

In [9]:
#REGARDER DE OU VIENNENT LES NB_GENES !!!!

"""
Obs: cells
Var: peaks
X: information about open chromatine ?

"""
Visualize_h5_file('atac_ad.h5ad', 'obs')

Keys available in the HDF5 file: ['X', 'layers', 'obs', 'obsm', 'obsp', 'uns', 'var', 'varm', 'varp']

Dimension: (98,)
Value of dataset '_index': [b's15t1p2sq1' b's15t2p2sq1' b's15t3p2sq1' b's15t4p2sq1' b's15t5p2sq1'
 b's15t6p2sq1' b's15t7p2sq1' b's15t8p2sq1' b's1t1p1sq1' b's1t2p1sq1'
 b's1t3p1sq1' b's1t4p1sq1' b's1t5p2sq1' b's1t6p2sq1' b's1t7p2sq1'
 b's1t8p2sq1' b's7t1p1sq1' b's7t2p1sq1' b's7t3p1sq1' b's7t4p1sq1'
 b's7t5p1sq1' b's7t6p1sq1' b's7t7p1sq1' b's7t8p1sq1' b's2t1p3sq2'
 b's2t2p3sq2' b's2t3p3sq2' b's2t4p3sq2' b's2t5p3sq2' b's2t6p3sq2'
 b's2t7p3sq2' b's2t8p3sq2' b's3t1p3sq2' b's3t2p3sq2' b's3t3p3sq2'
 b's3t4p3sq2' b's3t5p4sq2' b's3t6p4sq2' b's3t7p4sq2' b's3t8p4sq2'
 b's4t1p4sq2' b's4t2p4sq2' b's4t3p4sq2' b's4t4p4sq2' b's4t5p4sq2'
 b's4t6p4sq2' b's4t7p4sq2' b's4t8p4sq2' b's5t1p5sq3' b's5t2p5sq3'
 b's5t3p5sq3' b's5t4p5sq3' b's5t5p5sq3' b's5t6p5sq3' b's5t7p5sq3'
 b's5t8p5sq3' b's6t1p5sq3' b's6t2p5sq3' b's6t3p5sq3' b's6t4p5sq3'
 b's6t5p6sq3' b's6t6p6sq3' b's6t7p6sq3' b's6t8p6sq3' b's9t1p6sq3'
 b's9t2p6sq3' b's9t3p6sq3' b's9t4p6sq3' b's9t5p6sq3' b's9t6p6sq3'
 b's9t7p6sq3' b's9t8p6sq3' b'AU565Repd1' b'AU565Repd2' b'HCC1937drep1'
 b'HCC1937drep2' b'HCC1954Repd1' b'HCC1954Repd2' b'HTBd26Repd1'
 b'HTBd26Repd2' b'MCF10Adrep1' b'MCF10Adrep2' b'MCF7drep1' b'MCF7drep2'
 b'MDAdMBd436Repd1' b'MDAdMBd436Repd2' b'MDAdMBd468dRepd3'
 b'MDAdMBd468dRepd4' b'MDAMB231crmdrep1' b'MDAMB231crmdrep2'
 b'Me16CcdHMECdRepd1' b'Me16CcdHMECdRepd2' b'ZRd75d1dRepd3'
 b'ZRd75d1dRepd4' b'ZRd75d1Repd1' b'ZRd75d1Repd2' b'ZRd75d30Repd1'
 b'ZRd75d30Repd2']
Dimension: (98,)
Value of dataset 'n_genes': [15261 20598 20253 20196 20640 19576 19722 18995 20264 19707 20392 20647
 19080 19906 19485 17731 20243 20318 20108 20307 20113 18604 20161 20072
 14366 16049 19754 18829 19045 17724 18557 16267 17928 15133 18059 18511
 17703 16663 16236 16846 13369 12159 12424 12374 13129 13189 14269 17673
 17109 15750 15905 15286 16097 14843 17048 18205 18704 18407 18684 17190
 18115 17979 18869 17926 16921 17621 16334 19068 18278 15731 19269 19775
 15149 15343 18197 18142 17307 17243 15068 14981 16425 16636 17744 17419
 14067 15189 17416 17352 16954 17527 15591 16028 16786 17520 17002 14031
 15027 14159]